document.write("<script src='common.js'></script>")
document.write("<script src='searching.js'></script>")
document.write("<script src='blocks.js'></script>")
document.write("<script src='load.js'></script>")
document.write("<script src='timelines.js'></script>")
document.write("<script src='init.js'></script>")
